---
apiVersion: v1
kind: Secret
metadata:
  name: mls-mls-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/mls-gateway-gitops
